$(document).ready(function () {
    $('select').material_select();

    $('input.autocomplete.player').autocomplete({
        data: {
            "Xuxu_blz": null,
            "Makino": null,
            "landstalker": null,
            "Yoshi | Maria Gadú das Trevas": null,
            "FTLTR | I love eroges": null,
            "Siegvriel": null,
            "Densetsu | Nikki": null,
            "FTLTR | Naruto": null,
            "koopao": null,
            "MeltySud | Canceris": null,
            ":jogadordejin: | Inso": null,
            "Boss | Kefka696": null,
            "VeryDeath": null,
            "Koller": null,
            "Zeppeli": null,
            "FIR CA | Lo-Fi": null,
            "NeloRosso": null,
            "matoii": null,
            "RWmkII": null,
            "Mudo": null,
            "FTLTR | Trema": null,
            "Thanatos": null,
            "Kaphwan_Fabi": null,
            "Dandy": null,
            "Predo Bidan": null,
            "Kurt": null,
            "Teresa": null,
            "019 | Hnkmeister": null,
            "FIR.HOH | Lider": null,
            "Blackheart": null,
            "Zazs": null,
            "Makino": null,
            "Vinn Aleixo": null,
            "Musketeer": null,
            "Yoshi | Maria Gadú das Trevas": null,
            "FTLTR | I love eroges": null,
            "Weslley Pato / BarrakObrahma": null,
            "FTLTR | KMRiku": null,
            "Pato Ninja | thebronxk": null,
            "TecniK": null,
            ":jogadordejin: | Inso": null,
            "Fuu": null,
            "Hicchan": null,
            "AmmySensei": null,
            "Mudo": null,
            "FTLTR | Trema": null,
            "Kaphwan_Fabi": null,
            "Klasfer": null,
            "Predo Bidan": null,
            "FTLTR | Raposao": null,
            "FTLTR | Takagi": null,
            "Zazs": null,
            "Hai<3 | ScrawtVermillion": null,
            "Makino": null,
            "TroubledEar42": null,
            "J-ISM": null,
            "TWO | ShadowCarnage": null,
            "Kuronekoekoeko": null,
            "potter": null,
            "kAA": null,
            "arjarath": null,
            "Luckzero": null,
            "Predo Bidan": null,
            "FIR.HOH | Lider": null,
            "SuperPants": null,
            "landstalker": null,
            "FS": null,
            "Densetsu | Nikki": null,
            "Fuu": null,
            "Shao": null,
            "Kurt": null,
            "FTLTR | Raposao": null,
            "Hai<3 | ScrawtVermillion": null,
            "Vinn Aleixo": null,
            "MeltySud | Canceris": null,
            "TWO | ShadowCarnage": null,
            ":jogadordejin: | Inso": null,
            "Precure | Rakuchan": null,
            "Shao": null,
            "Kawaiinso | Rosha": null,
            "Tyrr": null,
            "RWmkII": null,
            "Mu La Flaga": null,
            "Klasfer": null,
            "Predo Bidan": null,
            "Kurt": null,
            "Hai<3 | ScrawtVermillion": null,
        },
        limit: 5, // The max amount of results that can be shown at once. Default: Infinity.
        onAutocomplete: function (val) {
            // Callback function when value is autcompleted.
        },
        minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
    });

});